import pandas as pd
import joblib
import os

base = "e:/Infosys-project/ml"

# ── Dataset ───────────────────────────────────────────────────
irr = pd.read_csv(f"{base}/dataset/irrigation_data.csv")
print("=" * 55)
print("DATASET FILE")
print("=" * 55)
print(f"File       : ml/dataset/irrigation_data.csv")
print(f"Rows       : {len(irr)}")
print(f"Columns    : {len(irr.columns)}")
print(f"All columns: {list(irr.columns)}")
print(f"Target col : irrigation_needed")
target_counts = irr["irrigation_needed"].value_counts()
print(f"Target dist: {target_counts.to_dict()}")
print(f"Data source: SYNTHETIC (generated by ml/dataset/generate_dataset.py)")

# ── Processed data ────────────────────────────────────────────
X_train = pd.read_csv(f"{base}/processed_data/X_train.csv")
X_test  = pd.read_csv(f"{base}/processed_data/X_test.csv")
y_train = pd.read_csv(f"{base}/processed_data/y_train.csv").squeeze()
y_test  = pd.read_csv(f"{base}/processed_data/y_test.csv").squeeze()

print("\n" + "=" * 55)
print("PROCESSED DATA (after preprocessing)")
print("=" * 55)
print(f"X_train shape : {X_train.shape}  (rows x features)")
print(f"X_test shape  : {X_test.shape}")
print(f"y_train dist  : {y_train.value_counts().to_dict()}")
print(f"y_test  dist  : {y_test.value_counts().to_dict()}")
print(f"\nAll {len(X_train.columns)} features after encoding:")
for i, col in enumerate(X_train.columns):
    print(f"  {i+1:2d}. {col}")

# ── Model ─────────────────────────────────────────────────────
model = joblib.load(f"{base}/models/best_model.pkl")
results = joblib.load(f"{base}/models/results_summary.pkl")

print("\n" + "=" * 55)
print("BEST MODEL")
print("=" * 55)
print(f"Model type   : {type(model).__name__}")
print(f"n_estimators : {model.n_estimators}")
print(f"learning_rate: {model.learning_rate}")
print(f"max_depth    : {model.max_depth}")
print(f"subsample    : {model.subsample}")
print(f"random_state : {model.random_state}")

print("\n" + "=" * 55)
print("ALL MODEL RESULTS")
print("=" * 55)
print(results[["accuracy","precision","recall","f1","roc_auc"]].to_string())
